# Generated by Django 2.2.6 on 2019-10-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20191030_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(related_name='question_like', to='question.Profile', verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='question.Tag', verbose_name='Тэги'),
        ),
    ]
